package app.xodos2.ui.runtime

import android.content.Context
import android.util.Log
import java.io.File

/**
 * Manages the HUD environment file at $PREFIX/opt/hud.
 *
 * Exactly one (or none) of DXVK_HUD / MANGOHUD can be active at a time.
 * Selection is persisted in SharedPreferences and re-applied on demand.
 */
object HudManager {

    private const val TAG = "HudManager"
    private const val PREFS = "hud_manager"
    private const val PREF_MODE = "hud_mode"

    /** Mode stored in prefs and used by the drawer. */
    enum class Mode(val id: String) {
        NONE("none"),
        DXVK("dxvk"),
        MANGOHUD("mangohud");

        companion object {
            fun from(id: String?): Mode =
                entries.firstOrNull { it.id == id } ?: NONE
        }
    }

    /** <filesDir>/usr/opt/hud  ==  $PREFIX/opt/hud in the guest */
    fun hudFile(context: Context): File =
        File(context.filesDir, "usr/opt/hud")

    // ────────── Persistence ──────────

    fun currentMode(context: Context): Mode =
        Mode.from(
            context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                .getString(PREF_MODE, Mode.NONE.id)
        )

    // ────────── File content per mode ──────────

    private fun contentFor(mode: Mode): String = when (mode) {
        Mode.NONE -> ""
        Mode.DXVK ->
            """
            |# XoDos-Ark HUD configuration
            |# Generated by HudManager — do not edit manually
            |export MANGOHUD=0
            |export DXVK_HUD=fps,version,devinfo
            |""".trimMargin() + "\n"
        Mode.MANGOHUD ->
            """
            |# XoDos-Ark HUD configuration
            |# Generated by HudManager — do not edit manually
            |export MANGOHUD=1
            |export MANGOHUD_CONFIG=fps,ram,gpu_name,horizontal,horizontal_stretch,no_small_font,background_alpha=0.2,alpha=0.9
            |export DXVK_HUD=0
            |""".trimMargin() + "\n"
    }

    // ────────── Public API ──────────

    /**
     * Rewrites the hud file from scratch and persists [mode].
     * Returns true if the write succeeded (or was a no-op clear of an empty file).
     */
    fun applyMode(context: Context, mode: Mode): Boolean {
        // 1. Save preference first — even if the write fails, the UI stays consistent.
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putString(PREF_MODE, mode.id)
            .apply()

        // 2. Rewrite the file.
        val file = hudFile(context)
        return try {
            file.parentFile?.mkdirs()

            if (mode == Mode.NONE) {
                // Clear contents. Keep the file existing but empty so any
                // `source $PREFIX/opt/hud` in the wrapper stays a no-op instead
                // of erroring out.
                if (file.exists()) {
                    file.writeText("")
                    file.setReadable(true, false)
                    file.setWritable(true, false)
                    file.setExecutable(false)
                }
                Log.i(TAG, "HUD cleared (mode=NONE)")
            } else {
                // Truncate + write fresh content (File.writeText already truncates).
                file.writeText(contentFor(mode))
                file.setReadable(true, false)
                file.setWritable(true, false)
                file.setExecutable(false)
                Log.i(TAG, "HUD written: mode=${mode.id} -> ${file.absolutePath}")
            }
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to write ${file.absolutePath}", e)
            false
        }
    }

    /**
     * Re-applies the persisted mode on startup. Useful if the file was wiped
     * by a cache clear or a fresh install.
     */
    fun reapplyPersisted(context: Context) {
        applyMode(context, currentMode(context))
    }
}